apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: gateway-operator
    repoURL: https://charts.konghq.com
    targetRevision: 0.6.1
    helm:
      releaseName: gateway-operator
      parameters:
        - name: env.ENABLE_CONTROLLER_KONNECT
          value: "true"
        - name: global.webhooks.options.certManager.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true